name: D-32 Blog
meta_description: "D-32 Blog"

markdown: redcarpet
highlighter: true
logo: false
paginate: 10

baseurl:        ''
url:            'http://blog.d-32.com'
author:         'Dylan Marriott'
